### ISSUE TITLE
error when giving certificate 

### ISSUE THREAD

**Issue by cfoour** [xT-Development/xt-pdextras#3]
**[  script:xt-pdextras] SCRIPT ERROR: @xt-pdextras/server/sv_certs.lua:22: attempt to index a string value (local 'certs')**

i've added this to qbx_core/server/player.lua  `playerData.metadata.pdcerts = playerData.metadata.pdcerts or 'none'` and same problem

**Comment by xThrasherrr** [comment]
Fixed here: https://github.com/xT-Development/xt-pdextras/commit/69889f7865e97484907fe6a7c4eabb0e20257125
I forgot to add the required playerdata to the readme.
